Resources:
 ##VPC
  myVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true

  ## Private Subnet    
  privateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: us-east-2a
      VpcId: !Ref myVPC
      CidrBlock: 10.0.1.0/24
         
  ## Public Subnet    
  publicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: us-east-2b
      VpcId: !Ref myVPC
      CidrBlock: 10.0.2.0/24   

  ## IGW
  myIgw:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: IGW
      
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref myVPC
      InternetGatewayId: !Ref myIgw
      
  ##Route table
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref myVPC
      Tags:
        - Key: Name
          Value: Public Route
          
 ##EC2 instance
  Ec2Instance:
    Type: AWS::EC2::Instance
    Properties:
      VpcId: !Ref myVPC
      InstanceType: t2.micro
      ImageId: ami-06fcc1f0bc2c8943f # Amazon Linux AMI in N.Californias
      KeyName: california-kp
   
 